###
# database/store layer
# Start services/third-party services for development.
###

version: "3.7"

services:
  onepick.store.elastic:
    image: bitnami/elasticsearch:7.14.0
    user: root
    volumes:
      - elastic-data:/bitnami/elasticsearch/data
    environment:
      - ELASTICSEARCH_HEAP_SIZE=512m
    ports:
      - 9200:9200
      - 9300:9300

volumes:
  elastic-data:
    driver: local
